// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDTW24HUBkZh7OPIf301j90QCxHS2Kzsg',
    appId: '1:888955644660:web:800a9777e6295dd4408ca1',
    messagingSenderId: '888955644660',
    projectId: 'labinventory-9e648',
    authDomain: 'labinventory-9e648.firebaseapp.com',
    storageBucket: 'labinventory-9e648.firebasestorage.app',
    measurementId: 'G-LPY64E51NH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD38r4LTP5egdUkfF7tMC9ZCcjV3d9ACGY',
    appId: '1:888955644660:android:2a731a2277fdc940408ca1',
    messagingSenderId: '888955644660',
    projectId: 'labinventory-9e648',
    storageBucket: 'labinventory-9e648.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7UpPXWmCv1Z6x5w6DyW8uZc75Tih10xI',
    appId: '1:888955644660:ios:a98ee96995270a99408ca1',
    messagingSenderId: '888955644660',
    projectId: 'labinventory-9e648',
    storageBucket: 'labinventory-9e648.firebasestorage.app',
    iosBundleId: 'com.example.internshiptask',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7UpPXWmCv1Z6x5w6DyW8uZc75Tih10xI',
    appId: '1:888955644660:ios:a98ee96995270a99408ca1',
    messagingSenderId: '888955644660',
    projectId: 'labinventory-9e648',
    storageBucket: 'labinventory-9e648.firebasestorage.app',
    iosBundleId: 'com.example.internshiptask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDTW24HUBkZh7OPIf301j90QCxHS2Kzsg',
    appId: '1:888955644660:web:43ee5ba780d46f99408ca1',
    messagingSenderId: '888955644660',
    projectId: 'labinventory-9e648',
    authDomain: 'labinventory-9e648.firebaseapp.com',
    storageBucket: 'labinventory-9e648.firebasestorage.app',
    measurementId: 'G-ME2RMT5S5B',
  );
}
